// Provenance registry — the single source of truth for where every dataset comes from.
// Surfaced inline via <SourceTag/> and in full on the /sources page. Edit provenance HERE
// only; the UI reads from this so the tooltip and the Sources page never drift.
//
// HARD RULE (CLAUDE.md "Data integrity"): a metric may render only if it has a real entry
// here — a named official source, an as-of date, and a committed fetch script. No source → no UI.

export interface SourceMeta {
  id: string;
  label: string;       // what the metric is, e.g. "Ward population"
  short: string;       // compact inline tag, e.g. "ONS · mid-2024"
  source: string;      // official dataset name
  publisher: string;
  datasetId: string;   // e.g. "ONS NOMIS NM_2014_1"
  asOf: string;        // as-of period
  licence: string;
  sourceUrl: string;   // link to the official dataset (verified 200)
  scriptUrl: string;   // link to the committed generator script (reproducibility)
  note?: string;
}

const REPO = 'https://github.com/willspensley/brum-dashboard-/blob/main';

export const SOURCES: Record<string, SourceMeta> = {
  population: {
    id: 'population',
    label: 'Ward population',
    short: 'ONS · mid-2024',
    source: 'Small Area Population Estimates (2021-based), all ages, both sexes',
    publisher: 'Office for National Statistics',
    datasetId: 'ONS NOMIS NM_2014_1',
    asOf: 'Mid-2024',
    licence: 'Open Government Licence v3.0',
    sourceUrl: 'https://www.nomisweb.co.uk/datasets/pestsyoala',
    scriptUrl: `${REPO}/scripts/fetch-population.mjs`,
    note: '69 wards · sums to 1,183,618 = the ONS Birmingham LAD total (verified at generation).',
  },
  crime: {
    id: 'crime',
    label: 'Ward crime',
    short: 'data.police.uk',
    source: 'Street-level recorded crime (West Midlands Police)',
    publisher: 'Home Office · data.police.uk',
    datasetId: 'data.police.uk crimes-street API',
    asOf: 'Monthly (latest month shown in the dashboard header)',
    licence: 'Open Government Licence v3.0',
    sourceUrl: 'https://data.police.uk/data/',
    scriptUrl: `${REPO}/scripts/fetch-crime-wards.mjs`,
    note: 'Crimes aggregated to the 69 official wards by point-in-polygon; rate = count ÷ ONS population.',
  },
  crimeObservatory: {
    id: 'crimeObservatory',
    label: 'Ward crime — deep dive',
    short: 'WMP · City Observatory',
    source: 'Street-level recorded crime (West Midlands Police), ward-tagged',
    publisher: 'West Midlands Police · via Birmingham City Observatory',
    datasetId: 'west-midlands-police-crime',
    asOf: 'Monthly · 36-month series (latest month shown in the dashboard header)',
    licence: 'Open Government Licence v3.0',
    sourceUrl: 'https://cityobservatory.birmingham.gov.uk/explore/dataset/west-midlands-police-crime/',
    scriptUrl: `${REPO}/scripts/fetch-crime-observatory.mjs`,
    note: 'Recorded offences per 1,000 residents per ward, with a 36-month trend, category mix and outcomes. Rate = offences ÷ ONS population (derived). Aggregates only — raw street rows are never shipped to the browser.',
  },
  universalCredit: {
    id: 'universalCredit',
    label: 'Universal Credit claimants',
    short: 'DWP · monthly',
    source: 'People on Universal Credit (household heads + partners)',
    publisher: 'Department for Work & Pensions · via Birmingham City Observatory',
    datasetId: 'number-of-people-on-universal-credit-wmca-wards-2025',
    asOf: 'Monthly (latest month shown in the dashboard header)',
    licence: 'Open Government Licence v3.0',
    sourceUrl:
      'https://cityobservatory.birmingham.gov.uk/explore/dataset/number-of-people-on-universal-credit-wmca-wards-2025/',
    scriptUrl: `${REPO}/scripts/fetch-uc.mjs`,
    note: 'Administrative hard count (not modelled). WMCA ward records filtered to the 69 official Birmingham wards (E05011118–E05011186).',
  },
  ucEmployment: {
    id: 'ucEmployment',
    label: 'UC claimants in employment',
    short: 'DWP · monthly',
    source: 'Percentage of Universal Credit claimants who are in employment',
    publisher: 'Department for Work & Pensions · via Birmingham City Observatory',
    datasetId: 'percentage-universal-credit-claimants-in-employment-birmingham-wards',
    asOf: 'Monthly (latest month shown in the dashboard header)',
    licence: 'Open Government Licence v3.0',
    sourceUrl:
      'https://cityobservatory.birmingham.gov.uk/explore/dataset/percentage-universal-credit-claimants-in-employment-birmingham-wards/',
    scriptUrl: `${REPO}/scripts/fetch-uc-employment.mjs`,
    note: 'Native percentage (not modelled, no derivation). 69 Birmingham wards. The "in-work poverty" signal — claimants also in paid work.',
  },
  claimantCount: {
    id: 'claimantCount',
    label: 'Claimant count',
    short: 'DWP · monthly',
    source: 'Claimant count by sex and age (unemployment-related benefits: UC searching-for-work + JSA)',
    publisher: 'Department for Work & Pensions · via Birmingham City Observatory',
    datasetId: 'claimant-count-by-sex-birmingham-wards-latest + claimant-count-birmingham-wards-5years',
    asOf: 'Monthly (latest month shown in the dashboard header)',
    licence: 'Open Government Licence v3.0',
    sourceUrl:
      'https://www.cityobservatory.birmingham.gov.uk/explore/dataset/claimant-count-by-sex-birmingham-wards-latest/',
    scriptUrl: `${REPO}/scripts/fetch-claimant-count.mjs`,
    note: 'Administrative counts, DWP-rounded to the nearest 5. The % is DWP\'s native "claimants as a proportion of residents aged 16-64" (not derived). 69 official wards; 5-year monthly series for trends.',
  },
  housingBenefit: {
    id: 'housingBenefit',
    label: 'Housing Benefit take-up',
    short: 'DWP · monthly',
    source: '% of households in receipt of Housing Benefit',
    publisher: 'Department for Work & Pensions · via Birmingham City Observatory',
    datasetId: 'percentage-households-in-receipt-of-housing-benefits-wmca',
    asOf: 'Monthly (latest month shown in the dashboard header)',
    licence: 'Open Government Licence v3.0',
    sourceUrl:
      'https://www.cityobservatory.birmingham.gov.uk/explore/dataset/percentage-households-in-receipt-of-housing-benefits-wmca/',
    scriptUrl: `${REPO}/scripts/fetch-housing-benefit.mjs`,
    note: 'Administrative hard count (not modelled). Published at LOCAL-AUTHORITY level only — there is no ward breakdown. Shown as Birmingham vs the other West Midlands boroughs, with the DWP regional/national benchmarks.',
  },
  childPoverty: {
    id: 'childPoverty',
    label: 'Children in low-income families',
    short: 'DWP/HMRC · annual',
    source: '% of children aged 0-15 in absolute low-income families (below 60% of 2010/11 median, inflation-adjusted)',
    publisher: 'DWP/HMRC · via Birmingham City Observatory',
    datasetId: 'percentage-of-children-in-absolute-low-income-families-aged-0-15-birmingham-wards',
    asOf: 'Annual, 2015/16 → latest (shown in the dashboard header)',
    licence: 'Open Government Licence v3.0',
    sourceUrl:
      'https://www.cityobservatory.birmingham.gov.uk/explore/dataset/percentage-of-children-in-absolute-low-income-families-aged-0-15-birmingham-wards/',
    scriptUrl: `${REPO}/scripts/fetch-child-poverty.mjs`,
    note: 'Native ward % (administrative, not modelled). 69 wards × 10-year series. Benchmarks are the REAL Birmingham-LA and England-mean series from the companion LA dataset.',
  },
  benefitsBill: {
    id: 'benefitsBill',
    label: 'Benefits Bill (DWP expenditure)',
    short: 'DWP · 2024/25',
    source: 'Benefit expenditure by local authority, 2024/25 outturn (£m nominal)',
    publisher: 'Department for Work & Pensions',
    datasetId: 'Benefit expenditure and caseload tables 2025',
    asOf: '2024/25 financial year',
    licence: 'Open Government Licence v3.0',
    sourceUrl: 'https://assets.publishing.service.gov.uk/media/693ffb536a12691d48491fb3/benefit-expenditure-by-local-authority-2024-25.ods',
    scriptUrl: `${REPO}/scripts/fetch-benefits-bill.mjs`,
    note: 'The exact file: benefit-expenditure-by-local-authority-2024-25.ods (from the DWP "Benefit expenditure and caseload tables 2025" publication page). One sheet per year ("2002-03"…"2024-25"); Birmingham is row E08000025 on each. A copy is archived in-repo at archive/. Column mapping re-validated at every fetch against each sheet\'s own Total. Excludes Child Benefit (HMRC).',
  },
  pipConditions: {
    id: 'pipConditions',
    label: 'PIP by medical condition (GB)',
    short: 'DWP · 2013/14–2024/25',
    source: 'PIP expenditure by reported medical condition — category + granular condition, nominal & real (2025/26 prices), WA/PA splits',
    publisher: 'Department for Work & Pensions',
    datasetId: 'pip-expenditure-2024-to-2025.ods',
    asOf: '2024/25 financial year (series from 2013/14)',
    licence: 'Open Government Licence v3.0',
    sourceUrl: 'https://assets.publishing.service.gov.uk/media/695b8ddfa2fb6c15f98d1954/pip-expenditure-2024-to-2025.ods',
    scriptUrl: `${REPO}/scripts/fetch-pip-conditions.mjs`,
    note: 'GREAT BRITAIN ONLY — no sub-national £-by-condition exists anywhere. Validated at every fetch: category sum matches the by-LA workbook\'s GB PIP row; condition sheet reconciles with the category sheet. Copy archived in-repo at archive/.',
  },
  constituencyMoney: {
    id: 'constituencyMoney',
    label: 'Constituency Money Map (DWP £)',
    short: 'DWP · 2024/25',
    source: 'Benefit expenditure by parliamentary constituency, 2024/25 outturn (£m nominal, 2024 boundaries)',
    publisher: 'Department for Work & Pensions',
    datasetId: 'benefit-expenditure-by-parliamentary-constituency-2024-25.ods — sheets "2024-25" + "UC_(PC24)"',
    asOf: '2024/25 financial year (UC trend 2019/20→2024/25)',
    licence: 'Open Government Licence v3.0',
    sourceUrl: 'https://assets.publishing.service.gov.uk/media/693ffc50c72b0f8ccf33d788/benefit-expenditure-by-parliamentary-constituency-2024-25.ods',
    scriptUrl: `${REPO}/scripts/fetch-constituency-money.mjs`,
    note: 'Actual DWP accounts, per-constituency rows each checksum-validated against the workbook\'s own Total. Copy archived in-repo at archive/. Constituencies straddle the LA boundary so their sum ≠ the Birmingham LA figure exactly (drift logged at every fetch). No ward-level £ exists.',
  },
  twoChild: {
    id: 'twoChild',
    label: 'Two-child limit (final statistics)',
    short: 'DWP · Apr 2026',
    source: 'UC statistics on the two child limit policy, April 2026 (final release — policy abolished 6 Apr 2026)',
    publisher: 'Department for Work & Pensions',
    datasetId: 'data-tables-universal-credit-statistics-two-child-limit-april-2026',
    asOf: 'April 2026',
    licence: 'Open Government Licence v3.0',
    sourceUrl: 'https://www.gov.uk/government/statistics/universal-credit-claimants-statistics-on-the-two-child-limit-policy-april-2026',
    scriptUrl: `${REPO}/scripts/fetch-two-child.mjs`,
    note: 'Constituency level — no ward breakdown exists. £ gains are DERIVED: children denied an element × the official child-element rate (£292.81/month). Cross-checked: constituency sum vs LA total at every fetch.',
  },
  wrongPayments: {
    id: 'wrongPayments',
    label: 'Wrong Payments (fraud & error leakage)',
    short: 'DWP · FYE 2025 rates',
    source: 'National fraud/error overpayment rates × Birmingham LA benefit expenditure',
    publisher: 'Department for Work & Pensions',
    datasetId: 'fraud-and-error-fye-2025 × benefit-expenditure-by-local-authority-2024-25',
    asOf: '2024/25 spend × FYE 2025 rates',
    licence: 'Open Government Licence v3.0',
    sourceUrl: 'https://www.gov.uk/government/statistics/fraud-and-error-in-the-benefit-system-financial-year-2024-to-2025-estimates/fraud-and-error-in-the-benefit-system-financial-year-ending-fye-2025',
    scriptUrl: `${REPO}/scripts/fetch-wrong-payments.mjs`,
    note: 'ILLUSTRATIVE / DERIVED. DWP does not publish LA-level fraud/error £. Each Birmingham benefit line × the matching national overpayment rate. Not a city audit. Small lines without a benefit-specific rate use the 3.3% all-benefit rate.',
  },
  ucWeather: {
    id: 'ucWeather',
    label: 'UC Money Weather (ward caseload over time)',
    short: 'DWP · Stat-Xplore',
    source: 'People on Universal Credit by ward (monthly) + Birmingham UC £ from LA expenditure tables',
    publisher: 'Department for Work & Pensions',
    datasetId: 'UC_Monthly + benefit-expenditure-by-local-authority',
    asOf: 'Monthly caseload; annual £',
    licence: 'Open Government Licence v3.0',
    sourceUrl: 'https://stat-xplore.dwp.gov.uk/',
    scriptUrl: `${REPO}/scripts/fetch-uc-weather.mjs`,
    note: 'Ward figures are caseload counts, not £. City UC £ is LA accounts. Per-1,000 is derived from ONS mid-2024 population.',
  },
  ucPayments: {
    id: 'ucPayments',
    label: 'UC Payments (household award intensity)',
    short: 'DWP · Stat-Xplore households',
    source:
      'Households on Universal Credit — count, mean Payment Amount, award-size bands, family type (Birmingham LA)',
    publisher: 'Department for Work & Pensions',
    datasetId: 'UC_Households (Households on Universal Credit)',
    asOf: 'Monthly (latest in proposal)',
    licence: 'Open Government Licence v3.0',
    sourceUrl: 'https://stat-xplore.dwp.gov.uk/',
    scriptUrl: `${REPO}/scripts/fetch-uc-payments.mjs`,
    note:
      'LA-level only. Unit is households, not people. Mean Payment Amount is £ per household in the assessment period — not annual Benefits Bill UC expenditure (that remains a separate accounts series). No ward-level accounting £.',
  },
  familyModel: {
    id: 'familyModel',
    label: 'Family Support Model (illustrative)',
    short: 'Rates + Bham UC means',
    source:
      'GOV.UK statutory benefit rates 2026/27 + Stat-Xplore Birmingham UC household means by family type',
    publisher: 'Department for Work & Pensions / HMRC',
    datasetId: 'Benefit rates 2026-27 + UC_Households means',
    asOf: 'Rates 2026/27; means from latest UC payments pull',
    licence: 'Open Government Licence v3.0',
    sourceUrl:
      'https://www.gov.uk/government/publications/benefit-and-pension-rates-2026-to-2027/proposed-benefit-and-pension-rates-2026-to-2027',
    scriptUrl: `${REPO}/scripts/fetch-family-model.mjs`,
    note:
      'ILLUSTRATIVE. Not a real household. Not linked microdata. Couples have one UC claim. Stacked max rates assume eligibility that is rare in combination. Housing omitted (rent-specific).',
  },
  pipPlace: {
    id: 'pipPlace',
    label: 'PIP Place (ward caseload + city £ + GB conditions)',
    short: 'DWP · Stat-Xplore + accounts',
    source: 'PIP cases by ward; Birmingham PIP £; GB PIP by medical condition; Bham disability category counts',
    publisher: 'Department for Work & Pensions',
    datasetId: 'PIP_Monthly_new + LA expenditure + pip-expenditure-by-condition',
    asOf: 'Quarterly caseload; annual £',
    licence: 'Open Government Licence v3.0',
    sourceUrl: 'https://stat-xplore.dwp.gov.uk/',
    scriptUrl: `${REPO}/scripts/fetch-pip-place.mjs`,
    note: 'Ward = caseload only. Condition £ is Great Britain only. Category mix is reported admin classification, not a fraud measure.',
  },
  ucStage: {
    id: 'ucStage',
    label: 'UC Stage 3D (extruded ward caseload)',
    short: 'Three.js · same as UC Weather',
    source: 'Presentation layer over UC Money Weather (Stat-Xplore ward caseload + LA UC £)',
    publisher: 'Department for Work & Pensions / Ozzy stage',
    datasetId: 'uc-weather → Three.js extrusion',
    asOf: 'Same series as UC Money Weather',
    licence: 'Open Government Licence v3.0 (underlying data)',
    sourceUrl: 'https://stat-xplore.dwp.gov.uk/',
    scriptUrl: `${REPO}/scripts/fetch-uc-stage.mjs`,
    note: '3D height encodes caseload intensity only — not ward £.',
  },
  pipStage: {
    id: 'pipStage',
    label: 'PIP Stage 3D (extruded ward caseload)',
    short: 'Three.js · same as PIP Place',
    source: 'Presentation layer over PIP Place data',
    publisher: 'Department for Work & Pensions / Ozzy stage',
    datasetId: 'pip-place → Three.js extrusion',
    asOf: 'Same series as PIP Place',
    licence: 'Open Government Licence v3.0 (underlying data)',
    sourceUrl: 'https://stat-xplore.dwp.gov.uk/',
    scriptUrl: `${REPO}/scripts/fetch-pip-stage.mjs`,
    note: '3D height encodes PIP caseload only — not ward £ or fraud.',
  },
  ozzyStage: {
    id: 'ozzyStage',
    label: 'Ozzy Stage (dual UC + PIP 3D theatre)',
    short: 'Three.js dual layer',
    source: 'Combined UC Weather + PIP Place caseload series in one interactive stage',
    publisher: 'Department for Work & Pensions / Ozzy stage',
    datasetId: 'uc-weather + pip-place → dual extrusion',
    asOf: 'Combined parent series',
    licence: 'Open Government Licence v3.0 (underlying data)',
    sourceUrl: 'https://stat-xplore.dwp.gov.uk/',
    scriptUrl: `${REPO}/scripts/fetch-ozzy-stage.mjs`,
    note: 'Theatre mode. Toggle UC/PIP. Heights are caseload, not money.',
  },
  education: {
    id: 'education',
    label: 'Qualifications',
    short: 'Census 2021',
    source: 'Census 2021, table TS067 (highest level of qualification)',
    publisher: 'Office for National Statistics',
    datasetId: 'ONS NOMIS NM_2084_1',
    asOf: 'Census 2021 (frozen until 2031)',
    licence: 'Open Government Licence v3.0',
    sourceUrl: 'https://www.nomisweb.co.uk/sources/census_2021_ts',
    scriptUrl: `${REPO}/scripts/fetch-education-data.mjs`,
    note: '% of usual residents aged 16+. 69 wards.',
  },
  flyTipping: {
    id: 'flyTipping',
    label: 'Fly-tipping incidents per 1,000 people',
    short: 'Defra · annual',
    source: 'Fly-tipping incidents per 1,000 people (WasteDataFlow), local authority',
    publisher: 'Department for Environment, Food and Rural Affairs · via Birmingham City Observatory',
    datasetId: 'fly-tipping-incidents-per-1000-people-wmca',
    asOf: 'Annual (latest period shown in the dashboard header)',
    licence: 'Open Government Licence v3.0',
    sourceUrl:
      'https://www.cityobservatory.birmingham.gov.uk/explore/dataset/fly-tipping-incidents-per-1000-people-wmca/',
    scriptUrl: `${REPO}/scripts/fetch-fly-tipping.mjs`,
    note: 'Administrative rate (incidents ÷ ONS mid-year population × 1,000). LOCAL-AUTHORITY level only — no ward breakdown. Seven WM metro boroughs plus published WMCA and England means.',
  },
};
